export enum NotificationSeverity {
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
}

export enum NotificationIconKey {
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_REJECTED = 'BOOKING_REJECTED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_CREDITED = 'PAYMENT_CREDITED',

  TRIP_REMINDER = 'TRIP_REMINDER',
  BOOKING_REQUEST = 'BOOKING_REQUEST',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',

  CAR_APPROVED = 'CAR_APPROVED',
  CAR_REJECTED = 'CAR_REJECTED',
  CAR_APPROVAL_PENDING = 'CAR_APPROVAL_PENDING',
  CAR_OWNER_APPROVAL = 'CAR_OWNER_APPROVAL',

  ALERT = 'ALERT',
  DISPUTE_REPORTED = 'DISPUTE_REPORTED',
}
